### PR TITLE
MODULES-8044: upgrade Oracle Java 8 to 181, make it the default release

### PR DESCRIPTION
**Pull request by ojongerius**

### CODE REVIEW

**Comment by fculpo** [comment]
You should maybe open a ticket on their JIRA, and link this PR to it

**Comment by ojongerius** [comment]
@fculpo I went through the motions of raising https://tickets.puppetlabs.com/browse/MODULES-8044 . Hope it helps 😄

**Comment by david22swan** [comment]
@ojongerius Could you rebase your changes please.

**Comment by ojongerius** [comment]
Have rebased my changes.

**Comment by david22swan** [comment]
screen shot 2018-11-05 at 10 13 45 am

**Pull request merged**
