### PR TITLE
Fix OpenJDK paths on Debian based OS with ARM

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Either this or GH-322 needs to go in first and then the other PR adjusted.

**Comment by david22swan** [comment]
@mmoll  Associated PR has been merged.

**Comment by mmoll** [comment]
rebased and adjusted :)

**Comment by david22swan** [comment]
screen shot 2018-10-12 at 4 46 14 pm

**Pull request merged**
