### PR TITLE
Support ubuntu vivid

### PR DESCRIPTION
**Pull request by cypherfox**
Add support for vivid (Ubuntu 15.04). 

I upgraded the default Java Version to use to 8, since it is available as package from Canonical. If someone gives me some pointers on the Oracle packages, I will happily add them. I use only OpenJDK myself

### CODE REVIEW

**Comment by igalic** [comment]
should we add this to the list of supported platforms?

**Comment by mhaskel** [comment]
@igalic if you mean in the metadata, no. That's seems to just be the officially supported oses.

**Comment by mhaskel** [comment]
@cypherfox This needs to be squashed to a single commit.

**Comment by cypherfox** [comment]
@mhaskel done

**Comment by mhaskel** [comment]
Great, thanks @cypherfox !

**Pull request merged**
