### PR TITLE
(FACT-1754) search for matching line with java version

### PR DESCRIPTION
**Pull request by shuebnersr**
FACT-1754: fact "java_version" fails when JAVA_TOOL_OPTIONS is used

Solution: do not just try to read java version from first line, but search for the matching line from java output.

Note: as in the original code, the fix appears three times - I think it is on purpose to not introduce new functions in this scope.

### CODE REVIEW

**Comment by shuebnersr** [comment]
CI checks failed, will improve code.

**Comment by tphoney** [comment]
Thanks for the PR, keep up the good work @shuebnersr !

**Comment by tphoney** [comment]
There still seems to be issues on the unit tests. getting closer 👍

**Comment by shuebnersr** [comment]
Fixed the unit test for "other systems" (see above), but one of the other two tests is also broken. Still on it, never used Ruby before . :-)

**Comment by tphoney** [comment]
Many thanks for your continued persistence @shuebnersr

**Comment by shuebnersr** [comment]
Code improved, CI checks now succeed.

**Comment by tphoney** [comment]
Great work @shuebnersr  !!!

**Comment by shuebnersr** [comment]
You're welcome, @tphoney! And thanks a lot for the support and the great tool!

**Pull request merged**
