### PR TITLE
Fix up rspec deprecation warnings.

### PR DESCRIPTION
**Pull request by alexharv074**

### CODE REVIEW

**Comment by tphoney** [comment]
@alexharv074 apologies for the close and reopen. accidental click

**Comment by tphoney** [comment]
Great work !!

**Comment by alexharv074** [comment]
@tphoney  Not sure if you noticed but the build was red before the merge.

```
  incompatible OSs
    is_expected.to fail on windows 8.1 (FAILED - 1)
    is_expected.to fail on Darwin 13.3.0 (FAILED - 2)
    is_expected.to fail on AIX 7100-02-00-000 (FAILED - 3)
    is_expected.to fail on AIX 6100-07-04-1216 (FAILED - 4)
    is_expected.to fail on AIX 5300-12-01-1016 (FAILED - 5)
```

Was that something that was already broken?  I don't see how my change would have caused that.

**Comment by tphoney** [comment]
I sure did :) #168 will fix this issue. Thanks for being vigilant. @alexharv074

**Comment by alexharv074** [comment]
Great thanks!

**Pull request merged**
