### PR TITLE
allow latest archive version as dependency

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by HelenCampbell** [comment]
Made a release ticket too, but it likely won't get done until people free up after Puppet conf!

**Comment by bastelfreak** [comment]
Thanks!

**Comment by alexjfisher** [comment]
@HelenCampbell Any news on the release?

**Comment by HelenCampbell** [comment]
@alexjfisher Thanks for reminding me about this! I've handed off the release to a colleague and it should be out by next week :)

**Pull request merged**
