### PR TITLE
Add proxy options for Oracle Java

### PR DESCRIPTION
**Pull request by edestecd**
We need to download the rpm through a proxy.

### CODE REVIEW

**Comment by edestecd** [comment]
@eputnam rebased!

**Comment by edestecd** [comment]
Any feedback on this?  What can I do?

**Comment by edestecd** [comment]
rebased again...

**Comment by eputnam** [comment]
@edestecd sorry for falling off the planet there. i'll look at this today.

**Comment by edestecd** [comment]
No problem.  Do we need another rebase?

**Comment by eputnam** [comment]
Nope, we're good!

**Pull request merged**
