### PR TITLE
Add support for Debian 12 (Bookworm)

### PR DESCRIPTION
**Pull request by NITEMAN**
## Summary
Add support for Debian 12

## Additional Context
N/A

## Related Issues (if any)
#566

## Checklist
- [x] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [x] Manually verified. (For example `puppet apply`)

### CODE REVIEW

**Comment by 104ru** [comment]
Is this happening? Three months since Debian 12 release...

**Comment by mferstl** [comment]
@malikparvez is puppetlabs/modules the right team for this issue?

**Comment by malikparvez** [comment]
@mferstl yes it is the right team, let me check with the team for latest update on this...

**Comment by malikparvez** [comment]
@mferstl as puppet agent does not support deb 12 yet so there is no point in having this on modules and I cannot see this happening in  this quarter of the year hopefully it will be done in first quarter of new year.

**Comment by BuJo** [comment]
Just to confirm that the branch works.  Puppet works very well on Debian 12 and the branch supporting Debian 12 works like a charm on a few hundred puppet nodes here.

**Comment by alaunay** [comment]
> @mferstl as puppet agent does not support deb 12 yet so there is no point in having this on modules and I cannot see this happening in this quarter of the year hopefully it will be done in first quarter of new year.

I fail to see why we should wait for puppetserver for Debian 12, as the include 7.23 puppet agent included with Debian 12 works very well with whatever version of puppetserver you're using. We are using puppetserver 8 on Debian 11, and /all/ our other servers are Debian 12 with the stock 7.23 agent.

What's the point on waiting ? If Puppet as a company has trouble supporting Debian, let it be known. Apart from that, I don't understand the trouble, there's no technical blockage here.

**Comment by MinePlugins** [comment]
Bump

**Comment by ekohl** [comment]
I've opened https://github.com/puppetlabs/puppetlabs-java/pull/585 as an alternative, which should make it easier to support multiple versions in the future.

**Comment by NITEMAN** [comment]
Closing, superseded by #585

**Pull request closed without merging**
