### PR TITLE
MODULES-1527: Add windows basic support

### PR DESCRIPTION
**Pull request by fculpo**
Added support for windows 10 / server 2016 x64

### CODE REVIEW

**Comment by fculpo** [comment]
I think beaker fails because it is trying to install a windows only dependency.
How can we specify requirements per OS in metadata.json ?

**Comment by fculpo** [comment]
I will try to rebase today

**Comment by fculpo** [comment]
@david22swan rebased and ready to merge

**Comment by fculpo** [comment]
Also closes https://tickets.puppetlabs.com/browse/MODULES-8184

**Comment by david22swan** [comment]
@fculpo Apologies for the wait, there is currently some discussing on when and how to fully implement this.

**Comment by david22swan** [comment]
@fculpo We're still looking into it right now sorry. Discussion is still needed with the Windows team.

**Comment by david22swan** [comment]
@fculpo Apologies but I am now closing this PR as per the reasons given in:
https://tickets.puppetlabs.com/browse/MODULES-8184
I am apologize if you find this to be an inconvenience and hope to see more PRs opened by you in the future.
Best Wishes

**Pull request closed without merging**
